name: Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: TF Plan (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Prevents one failure from cancelling the other successful plans
      matrix:
        module: [ vpc, ecr, dns, ecs, cicd]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::026703081738:role/rtrp-github-ci-role
          aws-region: eu-north-1

      - name: Terraform Init & Validate
        working-directory: infra/${{ matrix.module }}
        run: |
          terraform init -input=false
          terraform validate

      - name: Terraform Plan
        working-directory: infra/${{ matrix.module }}
        run: terraform plan -input=false

  terraform-apply:
    name: TF Apply (${{ matrix.module }})
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production-infra # Single approval gate releases all matrix jobs
    strategy:
      fail-fast: false
      matrix:
        module: [ vpc, ecr, dns, ecs, cicd]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::026703081738:role/rtrp-github-ci-role
          aws-region: eu-north-1

      - name: Terraform Init & Apply
        working-directory: infra/${{ matrix.module }}
        run: |
          terraform init -input=false
          terraform apply -input=false -auto-approve